name: tripstory
description: A travel planning app

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# dependency_overrides:
  # firebase_core: 2.4.1
  # firebase_auth: 4.2.5
  # firebase_auth_web: 5.2.4
  # google_sign_in: 6.0.1