[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"

[build.env]
NIXPACKS_JAVA_VERSION = "17"

[build]
buildCommand = "cd backend && mvn -B -DskipTests clean package"