# Spring Boot Configuration for TripStory Backend
server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: tripstory-backend
  
  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:tripstory}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:password}
  
  # JPA Configuration
  jpa:
    database-platform: ${DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  
  # H2 Console (disabled in production)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}
      path: /h2-console
      settings:
        web-allow-others: true

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:80
    - http://frontend
    - http://frontend:80
    - https://thetripstory.com
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.tripstory: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Mapbox Configuration
mapbox:
  access-token: ${MAPBOX_ACCESS_TOKEN:}

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always